### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Skyrdow** [osusach/apolo-backend#1]
- [x] auth
- [ ] modo invitado (no guardar nada, permitir compilar el pdf)
- [ ] prototipo de renderizar pdf desde texto
- [ ] implementar almacenamiento de pruebas
- [ ] implementar banco de preguntas
